export { default as WelcomePage } from './Welcome/welcome.page'
export { default as LoginPage } from './Login/login.page'
export { default as SignupPage } from './Signup/signup.page'
export { default as UserListPage } from './UserList/user-list.page'
export { default as MapInfoPage } from './MapInfo/map-info.page'
export { default as NotFoundPage } from './NotFound/not-founf.page'
